---
kind: pipeline
type: docker
name: container-images

platform:
  os: linux
  arch: amd64

steps:
  - name: shellcheck
    image: koalaman/shellcheck-alpine:latest
    commands:
      - shellcheck --shell sh --check-sourced -S warning error --exclude SC1091 bin/*
    when:
      event:
        - pull_request
        - commit

  - name: build
    image: rancher/hardened-build-base:v1.17.5b7
    commands:
      - make all
    when:
      event:
        - tag
      instance:
        - drone-publish.rancher.io
  
  - name: docker-publish
    image: plugins/docker
    settings:
      dockerfile: Dockerfile
      repo: "rancher/ecm-distro-tools"
      username:
        from_secret: docker_username
      password:
        from_secret: docker_password
    volumes:
      - name: docker
        path: /var/run/docker.sock
    when:
      event:
        - tag
      instance:
        - drone-publish.rancher.io

volumes:
  - name: docker
    host:
      path: /var/run/docker.sock
