name: 'Setup ecm-distro-tools'
description: 'Installs ecm-distro-tools scripts to the PATH.'
inputs:
  version:
    description: 'The tag of the ecm-distro-tools release to install.'
    required: true
  install-script-version:
    description: 'The version of the install script to use.'
    required: false
    default: ${{ github.action_ref }}
runs:
  using: 'composite'
  steps:
  - env:
      INSTALL_SCRIPT_TAG: ${{ inputs.install-script-version }} 
    shell: bash
    run: |
      INSTALL_SCRIPT_PATH="${RUNNER_TEMP}/install.sh"
      TAG="${{ inputs.version }}"
      INSTALL_DIR=$HOME/.local/bin/ecm-distro-tools
      wget -O "${INSTALL_SCRIPT_PATH}" "https://raw.githubusercontent.com/rancher/ecm-distro-tools/${INSTALL_SCRIPT_TAG}/install.sh"
      chmod +x "${INSTALL_SCRIPT_PATH}" 
      ${INSTALL_SCRIPT_PATH} ${TAG}
      echo "${INSTALL_DIR}" >> "${GITHUB_PATH}"
      ls -al "${INSTALL_DIR}"
