name: 'Setup ecm-distro-tools'
description: 'Installs ecm-distro-tools scripts to the PATH.'
inputs:
  version:
    description: 'The tag of the ecm-distro-tools release to install.'
    required: true
runs:
  using: 'composite'
  steps:
  - shell: bash
    run: |
      INSTALL_SCRIPT_PATH="${RUNNER_TEMP}/install.sh"
      INSTALL_SCRIPT_TAG=${{ github.ref }}
      TAG="${{ inputs.version }}"
      DOWNLOAD_DIR=$HOME/.local/bin/ecm-distro-tools
      wget -O "${INSTALL_SCRIPT_PATH}" "https://raw.githubusercontent.com/rancher/ecm-distro-tools/${INSTALL_SCRIPT_TAG}/install.sh"
      chmod +x "${INSTALL_SCRIPT_PATH}" 
      ${INSTALL_SCRIPT_PATH} ${TAG}
      ls -al "$DOWNLOAD_DIR"
